### ISSUE TITLE
make_wiggle output format & get_count_vectors zero counts

### ISSUE THREAD

**Issue by bontus** [joshuagryphon/plastid#9] opened 2017-02-08 11:49 UTC
Dear Joshua,
Thanks for this tool, it is a great addition to the software I have been using so far.

I would like to mention two issues I encountered when using plastid:

1. All zero counts by _get_count_vectors_
After successfully determining p-site offsets for my set of samples as well as obtaining counts for different features (CDS, UTRs) via cs count, I have been trying to obtain codon-level counts for each gene via the get_count_vectors program. Unfortunately, although I use the same BAM files and offsets as for _metagene count_ and _cs count_, _get_count_vectors_ returns all zero count files.
I tried changing the annotation file format from BED12 to sorted GTF (official GENCODE v24 release for hg38), but to no avail.
Since I have PE data and only use the R1 reads, I checked whether read orientation and gene direction correspond via IGV and this is indeed the case. To be sure I flipped the orientation of all genes in the annotation file and re-ran the program, but still found no counts != 0.

To circumvent this issue, I used _make_wiggle_ to generate coverage profiles, which I have supplied to _get_count_vectors_.  However,  I am also not sure if _get_count_vectors_ can handle these files properly, since it's input formats comprise "BAM,bigwig,bowtie,wiggle" and my current test run only displays the following (after a runtime of >60 minutes) while the process keeps running using a core at 100%:

> get_count_vectors [2017-02-08 11:34:48]: Opening wiggle files RPF_sample1 ...

This brings me to the second issue I have encountered.

2. The output format of _make_wiggle_
_make_wiggle_ creates two .WIG files, one for each strand, which are by default in BEDGRAPH format. I find this extremely confusing, especially since there is no option to specify the output to be in WIGGLE format.

Kind regards

**Comment by joshuagryphon** [comment] 2017-02-09 17:45
Dear Bontus,

Thank you for your note. Here are my thoughts:

> 1. All zero counts by get_count_vectors
> After successfully determining p-site offsets for my set of samples as well as obtaining counts for different features (CDS, UTRs) via cs count, I have been trying to obtain codon-level counts for each gene via the get_count_vectors program. Unfortunately, although I use the same BAM files and offsets as for metagene count and cs count, get_count_vectors returns all zero count files.
I tried changing the annotation file format from BED12 to sorted GTF (official GENCODE v24 release for hg38), but to no avail.

This is indeed curious, because `metagene`, `cs`, and `get_count_vectors` all use the same argument parsers and methods to open BAM, BED, GTF, and other file formats. Plus, they're all passing their tests. When you have a moment, could you send me:

 0. Some info on your sequencing setup. It is paired end, but how many cycles did you read on each end? If your read are too long, they might be falling outside the default read length filters (config via `--min_length` and `--max_length`). That said, those default filters are the same in every script, so they should still behave similarly.

 1. The exact command-line you used to call each of these scripts?

 2. URLs for the genome annotation versions and genome build versions you are using? 

 3. Some info on which aligner you used, and the command-line arguments you supplied to it? Plastid has been extensively tested on output from Tophat and Bowtie, but I have been meaning to check its compatibility with STAR and other, newer, aligners. I try not to rely on alignment flags, but this could be another potential source of the difference

 4. Version numbers for: plastid, pysam, et c installed in your environment
 
> Since I have PE data and only use the R1 reads, I checked whether read orientation and gene direction correspond via IGV and this is indeed the case. To be sure I flipped the orientation of all genes in the annotation file and re-ran the program, but still found no counts != 0.

This is one of the first things I would have checked, too. Generally if you're using a dUTP-based paired end kit, R2 reads are the right orientation. Flipping the orientation in the annotation file should be equivalent.

I'm a little confused about which sequencing modality you're using though. Generally, for codon-level counts, one would be looking at ribosome profiling data. But in that case it is a bit unusual to do paired-end sequencing. 

> To circumvent this issue, I used make_wiggle to generate coverage profiles, which I have supplied to get_count_vectors. However, I am also not sure if get_count_vectors can handle these files properly, since it's input formats comprise "BAM,bigwig,bowtie,wiggle" and my current test run only displays the following (after a runtime of >60 minutes) while the process keeps running using a core at 100%:

I'm not surprised at the long runtime and heavy load if using wiggle/bedGraph files with a huge genome. Because they're not indexed, Plastid loads wiggle and bedGraph files entirely into memory before it begins processing, which makes it slow. A good stopgap would be to convert the bedGraph/wiggle files to `BigWig` using Jim Kent's `wigToBigWig` utility, and supply the argument `--countfile_format bigwig` to `get_count_vectors`

`get_count_vectors` can handle wiggle (both variableStep and fixedStep formats, as well as bedGraph) files, both of which should be specified using `--countfile_format wiggle` input format (the script will auto-detect which file type is used of those three).


> 2. The output format of make_wiggle
> make_wiggle creates two .WIG files, one for each strand, which are by default in BEDGRAPH format. I find this extremely confusing, especially since there is no option to specify the output to be in WIGGLE format.

By default, `make_wiggle` does export bedGraph files, but it can export variableStep wiggle files using the argument `--output_format variable_step`. `make_wiggle` will not export fixed-step wiggle files, because they tend to be way, way too large to deal with for most organisms. The name of the script is a little confusing, but it is what it is for historical reasons. Originally, it only exported variableStep wiggles; bedGraph support was added later.


Again, thank you for bringing this to my attention. We'll get to the bottom of it hopefully soon.

Cheers,
Josh

**Comment by bontus** [comment] 2017-02-15 11:02
Dear Josh,

For internal reasons, our sequencing facility used the NextSeq platform for our ribosome profiling runs and because of that created paired-end reads of 36nt each, however, the R2 reads are practically unusable due to low base quality and therefore I only use the R1 reads for all analyses. The majority of reads are 30-32nt long, so I sed `--min_length 28 --max_length 36` for all analysis.

As for annotation, I'm using GENCODE v24 (hg38, https://www.gencodegenes.org/releases/24.html), but converted the GTF to BED12 format [(download).](http://s000.tinyupload.com/index.php?file_id=05911556938161138566) My hg38 genome FASTA is the unmasked one from UCSC's goldenPath (http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/) and I ran TopHat v2.1.0 with `--transcriptome-index GENCODE_v24 --no-novel-juncs --no-coverage-search --read-mismatches 1 --max-multihits 20`.

Python stuff:

> biopython (1.68)
> cycler (0.10.0)
> Cython (0.25.2)
> functools32 (3.2.3.post2)
> matplotlib (2.0.0)
> numpy (1.12.0)
> pandas (0.19.2)
> pip (9.0.1)
> pyparsing (2.1.10)
> pysam (0.10.0)
> pytz (2016.10)
> scipy (0.18.1)
> six (1.10.0)
> subprocess32 (3.2.7)
> termcolor (1.1.0)
> twobitreader (3.1.4)

Interestingly, I installed plastid a while ago via pip, however it is not listed as installed via `pip list` (?), and if I try to install the newest version I end up with several times "Error compiling Cython file:", see [error log](http://s000.tinyupload.com/index.php?file_id=03745728551568586914)

Anyhow, since the executables still work fine, I call plastid using the following commands after mapping:
```
bedfile=gencode.v24.annotation_sorted.bed12;
metagene generate --quiet plastid_gencode_v24_hg38_orfs_metagene --landmark cds_start --annotation_files $bedfile --annotation_format BED;
cs generate -q --annotation_files $bedfile --annotation_format BED plastid_gencode_v24_hg38_orfs_cs;

psite plastid_gencode_v24_hg38_orfs_metagene_rois.txt $output --aggregate --constrain 10 20 --count_files $bamfile --min_length 28 --max_length 36;
cs count --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --min_length 28 --max_length 36 plastid_gencode_v24_hg38_orfs_cs_gene.positions RPF_counts_gene;
metagene count --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --min_length 28 --max_length 36 plastid_gencode_v24_hg38_orfs_metagene_rois.txt RPF_counts_metagene;
get_count_vectors --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --max_length 36 --annotation_files $bedfile --annotation_format BED RPF_codon_counts;
```

I have also tried the GENCODE GTF (after sorting + bgzip + tabix), but as I mentioned before, the results were the same for `get_count_vectors`. My next attempt will be to convert the input files to bigwig as you suggested and then retry counting.

Cheers

**Comment by joshuagryphon** [comment] 2017-02-17 00:56
Great! Thank you for sharing this info. I'll take a look and see if I can replicate what is going on. This probably won't happen before the weekend.

I'm curious that plastid isn't appearing in `pip list`, but that you can still find the executables. Something doesn't quite sit right with me about that- because those scripts need to import from plastid in order to function. At the very least, this suggests that the plastid scripts are running in a python environment that is distinct from the one `pip` is running in.

This raises some more questions:

 1. What OS, Python version, et c are you using?
 2. What version of Plastid do you have installed?
 3.  Are you using `conda` and/or `virtualenv`?
 4. When you installed `plastid`, how did you install it (e.g. from Git? from PyPI using `pip`? Using `easy_install`?)
 5. What happens when you type each of the following:
     - `cat $(which pip)`
     - `cat $(which metagene)`
     - `cat $(which get_count_vectors)` 
     - `which pip`
     - `which metagene`
     - `which get_count_vectors`

**Comment by bontus** [comment] 2017-02-20 14:43
Hi Josh,
The main problem might be that I am not a Python programmer myself and having some programs available both via pip and conda can be quite confusing ;)

The system is running Ubuntu 14.04.1 LTS (kernel 4.2.0-42-generic) with Python 2.7.12 and plastid 0.4.6 installed. Both `conda` (4.1.12) and `virtualenv` (15.0.3) are installed as well.
Further, `metagene` and `get_count_vectors` are located in `/usr/local/bin/`, while `pip` was installed via `conda` and is located in ~/miniconda2/bin/pip.

```
> cat $(which pip)
#!~/miniconda2/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

```
> cat $(which metagene)
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'plastid==0.4.6','console_scripts','metagene'
__requires__ = 'plastid==0.4.6'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('plastid==0.4.6', 'console_scripts', 'metagene')()
    )
```

```
> cat $(which get_count_vectors)
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'plastid==0.4.6','console_scripts','get_count_vectors'
__requires__ = 'plastid==0.4.6'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('plastid==0.4.6', 'console_scripts', 'get_count_vectors')()
    )
```

**Comment by joshuagryphon** [comment] 2017-02-20 20:21
Thank you for all of this info. `conda` has been and endless source of headache, because its sandboxes can be leaky and all kinds of strange and/or inconsistent behaviors can result. That said, since `metagene` and `get_count_vectors` are running in the same environment, they should behave similarly (i.e. both succeed, or both fail in the same way).

I'm working on replicating this issue on my end, but if `conda` is involved, I might not be able to accurately mimic the install on your system. It would be helpful if you could install `plastid` inside a clean `virtualenv`, outside of conda, without involving `conda`, and then re-run the scripts on your input files:

First, make sure `virtualenv` is free of `conda` (i.e. installed in your system environment, not nested within a `conda` environment). If `virtualenv` is stuck inside `conda`, try creating a new user account, logging in as that user, and doing user install of  `virtualenv` (`which pip; pip install --user virtualenv`):

```
# make sure virutalenv is outside of conda by checking path
$ cat $(which virtualenv)
```

Next, create a virtual environment and install Plastid:
```
$ virtualenv /path/to/my_virtualenv
$ source /path/to/my_virtualenv/bin/activate
(my_virtualenv) $ pip install numpy pysam cython
(my_virtualenv) $ pip install plastid
```

Then re-run `cs count` and `get_count_vectors` et c. as previously, but within the virtualenv:
```
(my_virtualenv) $ cs count --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --min_length 28 --max_length 36 plastid_gencode_v24_hg38_orfs_cs_gene.positions RPF_counts_gene

(my_virtualenv) $ metagene count --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --min_length 28 --max_length 36 plastid_gencode_v24_hg38_orfs_metagene_rois.txt RPF_counts_metagene

(my_virtualenv) $ get_count_vectors --fiveprime_variable --offset ${output}_p_offsets.txt --count_files $bamfile --max_length 36 --annotation_files $bedfile --annotation_format BED RPF_codon_counts
```


If things don't work, then there might be something with your data file that `Plastid` doesn't understand (although, in that case, again, every script touching the same sets of files should fail in the same way, because all argument parsing and file handling is performed by one module that all of the scripts import). We might be able to distinguish whether it is a behavior of your data files or a problem with `plastid` on your system if you run the `plastid` unit tests. First, download the test datset (available here: https://www.dropbox.com/s/h17go7tnas4hpby/plastid_test_data.tar.bz2?dl=0) and then unpack it into `/path/to/plastid/test/data`. Then, install `nose` (Python testing suite) inside the `virtualenv` and run a relevant subset of tests:

```
(my_virtualenv) $ pip install nose
(my_virtualenv) $ nosetests plastid.test.unit
(my_virtualenv) $ nosetests plastid.test.functional.test_get_count_vectors
(my_virtualenv) $ nosetests plastid.test.functional.test_cs
```

One last thing to check (on my end) would be the read length filters. Since your data is paired-end, Plastid might be measuring read length as the aligned length of both fragments (which might be non-sensical if one of each of your pairs is a footprint and something else just generated by your sequencing/cloning strategy). I'm pretty sure I coded defensively against this possibility, but it is possible that your reads might be excluded by the length filters, which would result in zero counts. That said, it should be zero counts in all scripts, not just in `get_count_vectors`

**Comment by bontus** [comment] 2017-02-21 08:53
Hi Josh,
I have been following your advice and set up a new virtualenv (outside of conda), however, plastid still fails to install properly via pip because of errors related to compiling Cython files [(error log)](http://s000.tinyupload.com/index.php?file_id=00092948023262995790).

**Comment by joshuagryphon** [comment] 2017-02-27 03:31
Hi @bontus ,

Just checked the latest error log you posted. The failure to compile in your `virtualenv` is due to https://github.com/joshuagryphon/plastid/issues/8, which is closed in the dev branch but not pushed into master yet. I'm sorry I had forgotten to mention this when I last wrote, but, in your virtualenv you'd need a version of `pysam` below 0.10.0 (in 0.10.0 they renamed a bunch of modules; so current Plastid releases work with 0.9.x but not 0.10.0)

For your bigwig files, what happens when you open them up in a genome browser (UCSC, IGV)? Do you see nothing there? or are there reads?

**Comment by joshuagryphon** [comment] 2017-02-28 04:22
Also, I have been digging into this. I downloaded the fasta files, your BED12, and the original GENCODE GTF2 annotation you mentioned above. The `metagene` roi file and `cs` positions files generated correctly, and I didn't see any mismatches in chromosome names between sequence files and annotations, ruling that out as a source of error.

I also re-checked my implementations of the size filters and read mapping rules, and, as I had intended, these are measuring read length by counting aligned positions, not by inferred alignment length, so single vs paired-end sequencing should not be at play.

Again, I'm still confused as to why you would be getting different behaviors from `get_count_vectors` versus `metagene` and `cs` when they're all calling the same methods to open the same files. The only other difference I can note is that you supply the arguments `--min_length 28` to ever script except `get_count_vectors`- but in this case `get_count_vectors` should be using the default minimum length of 25.


Unrelated, but I should add some notes that I should have mentioned before:

 - `get_count_vectors` gives counts by nucleotide position, not by codon (of course you can generate codon counts from nucleotide positions)

 - to work as intended `cs` and `metagene` need to be able to group transcripts by their gene names or IDs in order to calculate gene areas and maximal spanning windows, respectively. This information is present in GTF2 and GFF3 files, and, optionally can be included in a BigBed or extended BED file. But, this information is by default discarded in BED12 files. So, running `cs` and `metagene` on BED12 files will not produce the results described by the script. I will add warnings to the code on this matter before the next `plastid` release

**Comment by bontus** [comment] 2017-02-28 08:41
Hi Josh,
Reverting back to pysam 0.9.1.4 indeed fixed the installation issue, so I re-ran all previous analyses with the newly installed plastid and am happy to report that `get_count_vectors` now provides non-zero counts :)
Also, it is indeed good to know that the counts are on base-level, do you have any plans to do codon-level assignments as well? I believe these are actually more interesting for people analyzing ribo-seq data.
Concerning cs and metagene, I worked around this issue by changing the annotation file to contain only RefSeq transcripts with the longest ORF of a gene. Nonetheless, a warning would indeed be useful.

**Comment by joshuagryphon** [comment] 2017-02-28 13:18
Fantastic! I'm glad to hear that that solved the problem, but I am still curious how it arose.

For `get_count_vectors`, I had not planned to do codon-level assignments. I had not included it previously because a lot of people use plastid for things other than ribosome profiling. That said, I am happy to take feature requests! It is helpful to know what users need. When a request receives support from a bunch of individuals, then I consider adding it.

For now I'm going to close this issue. Please do write again if you have any questions or encounter more problems. And, good luck with your research!

**Closed by joshuagryphon** 2017-02-28 13:18 UTC
