### ISSUE TITLE
‘phase_by_size’ command-line script problem with Numpy(1.18.1)

### ISSUE THREAD

**Issue by rbmk1000** [joshuagryphon/plastid#40] opened 2020-04-16 22:02 UTC
Hello All,

This script does not run on my new linux box (plastid 0.4.8 py37h84994c4_4 bioconda; numpy 1.18.1) but runs on my old linux box (plastid 0.4.8 py27_0 bioconda; numpy 1.14.1) when modified for the directory structure there. It gives the float object error for phase_by_size - and another also another error  - on the new box. Advice gratefully appreciated. Thank you.

Script:

for i in *Coord.out.bam
	do samtools index $i
done

for i in *Coord.out.bam
	do psite /media/mrbmk1000/data/ms-pool01/annotationdb/cneoformans/FungDB-38_Cneoformans_cds_start200_rois.txt ${i%.*} --min_length 16 --max_length 34 --require_upstream --count_files $i
done

for i in *Coord.out.bam
	do phase_by_size /media/mrbmk1000/data/ms-pool01/annotationdb/cneoformans/FungDB-38_Cneoformans_cds_start200_rois.txt ${i%.*} \
                --count_files $i \
                --fiveprime --offset 12 \
                --codon_buffer 5 \
                --min_length 16 --max_length 34
done

New linux box:

(plastid) mrbmk1000@rbmk1000-home-linux:/media/mrbmk1000/data/ms-pool01/C_neoformans/ribo-seq/phasing$ bash ms-pool01_lazy_psites_cneoformans-200min16max34.sh*

---------------------------------------------------------------------------
RuntimeWarning
pysam.libcalignedsegment.PileupColumn size changed, may indicate binary
incompatibility. Expected 72 from C header, got 88 from PyObject
in /home/mrbmk1000/miniconda3/envs/plastid/lib/python3.7/importlib/_bootstrap.py, line 219:

217     module code)
218     """
219     return f(*args, **kwds)

---------------------------------------------------------------------------
psite [2020-04-16 16:24:55]: Opening ROI file /media/mrbmk1000/data/ms-pool01/annotationdb/cneoformans/FungDB-38_Cneoformans_cds_start200_rois.txt ...
psite [2020-04-16 16:24:55]: Opening count files rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out.bam ...
psite [2020-04-16 16:24:55]: Counted 17318765 total reads.
psite [2020-04-16 16:24:55]: Counted 1 ROIs ...
psite [2020-04-16 16:24:58]: Counted 1001 ROIs ...
psite [2020-04-16 16:25:01]: Counted 2001 ROIs ...
psite [2020-04-16 16:25:03]: Counted 3001 ROIs ...
psite [2020-04-16 16:25:07]: Counted 4001 ROIs ...
psite [2020-04-16 16:25:10]: Counted 5001 ROIs ...
psite [2020-04-16 16:25:12]: Counted 6001 ROIs ...
psite [2020-04-16 16:25:14]: Counted 6841 ROIs total.
psite [2020-04-16 16:25:15]: Plotting and determining offsets ...
psite [2020-04-16 16:25:15]: Writing offset table to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_p_offsets.txt ...
psite [2020-04-16 16:25:15]: Saving plot to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_p_offsets.png ...
psite [2020-04-16 16:25:15]: Done.
---------------------------------------------------------------------------
RuntimeWarning
pysam.libcalignedsegment.PileupColumn size changed, may indicate binary
incompatibility. Expected 72 from C header, got 88 from PyObject
in /home/mrbmk1000/miniconda3/envs/plastid/lib/python3.7/importlib/_bootstrap.py, line 219:

217     module code)
218     """
219     return f(*args, **kwds)

---------------------------------------------------------------------------
phase_by_size [2020-04-16 16:25:16]: Counted 17318765 total reads.
phase_by_size [2020-04-16 16:25:16]: Counted 1 ROIs ...
Traceback (most recent call last):
  File "/home/mrbmk1000/miniconda3/envs/plastid/bin/phase_by_size", line 11, in <module>
    load_entry_point('plastid==0.4.8', 'console_scripts', 'phase_by_size')()
  File "/home/mrbmk1000/miniconda3/envs/plastid/lib/python3.7/site-packages/plastid/bin/phase_by_size.py", line 190, in main
    counts = counts.reshape((len(counts)/3,3))
TypeError: 'float' object cannot be interpreted as an integer

Script running fine on old linux box with same data:

bp-data01@bp-data01:/bp-pool01/c_neoformans/ribo_seq/phasing$ ./lazy_psites_cneoformans-200min16max34.sh*
psite [2020-04-11 15:01:32]: Opening ROI file /bp-pool01/annotationdb/cneoformans/FungDB-38_Cneoformans_cds_start200_rois.txt ...
psite [2020-04-11 15:01:33]: Opening count files rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out.bam ...
psite [2020-04-11 15:01:33]: Counted 17318765 total reads.
psite [2020-04-11 15:01:33]: Counted 1 ROIs ...
psite [2020-04-11 15:01:40]: Counted 1001 ROIs ...
psite [2020-04-11 15:01:48]: Counted 2001 ROIs ...
psite [2020-04-11 15:01:54]: Counted 3001 ROIs ...
psite [2020-04-11 15:02:08]: Counted 4001 ROIs ...
psite [2020-04-11 15:02:14]: Counted 5001 ROIs ...
psite [2020-04-11 15:02:22]: Counted 6001 ROIs ...
psite [2020-04-11 15:02:28]: Counted 6841 ROIs total.
psite [2020-04-11 15:02:34]: Plotting and determining offsets ...
psite [2020-04-11 15:02:34]: Writing offset table to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_p_offsets.txt ...
psite [2020-04-11 15:02:34]: Saving plot to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_p_offsets.png ...
psite [2020-04-11 15:02:34]: Done.
phase_by_size [2020-04-11 15:02:35]: Counted 17318765 total reads.
phase_by_size [2020-04-11 15:02:35]: Counted 1 ROIs ...
phase_by_size [2020-04-11 15:02:39]: Counted 1001 ROIs ...
phase_by_size [2020-04-11 15:02:44]: Counted 2001 ROIs ...
phase_by_size [2020-04-11 15:02:48]: Counted 3001 ROIs ...
phase_by_size [2020-04-11 15:02:56]: Counted 4001 ROIs ...
phase_by_size [2020-04-11 15:03:00]: Counted 5001 ROIs ...
phase_by_size [2020-04-11 15:03:04]: Counted 6001 ROIs ...
phase_by_size [2020-04-11 15:03:08]: Counted 6841 ROIs total.
phase_by_size [2020-04-11 15:03:08]: Saving phasing table to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_phasing.txt ...
phase_by_size [2020-04-11 15:03:08]: Plotting to rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out_phasing.png ...

**Comment by joshuagryphon** [comment] 2020-05-19 22:52
Hi @rbmk1000 ,

I'm sorry for getting into this so far after you posted. I can confirm that `develop` (commit 3f71a3c) is working with the following configuration under Python 3.7, so the numpy issue should be fixed by working off of there until I manage to get the next release out (I'm morbidly behind on that- see issue #24 )

```ini
biopython==1.73
Cython==0.29.7
matplotlib==2.2.4
numpy==1.13.3
pandas==0.24.2
pysam==0.15.2
scipy==1.2.1
termcolor==1.1.0
twobitreader==3.1.6
```

The `RuntimeError` is of a type that isn't a huge problem, and can occur if the version of `numpy` or `pysam` against which `plastid` was compiled mismatches the one in the present environment. If tests in that environment pass (which you can run by installing `nose` into the conda env, and running it there), then you know you can safely ignore it.

Hope this helps. Since the issue is resolved in `develop`, which will eventually be pushed to master, I'm going to close this.

If I'm misunderstanding some context, please feel free to reopen.

Thanks & best,
Josh

**Closed by joshuagryphon** 2020-05-19 22:52 UTC
